### ISSUE TITLE
如何注册流程图节点啊？谢谢！

### ISSUE THREAD

**Issue by zhujingyi5419** [antvis/g6-editor#13]
官网给的是这个，不会用。给的参考链接也无法访问。
Flow.registerNode(name, {
  // 参考：https://lark.alipay.com/antv/rslism/anchor
  anchor,
  // 绘制
  draw(item) {
    return keyShape;
  },
}, extandShape);
G6.registerNode的方法试了也不行。有谁做过自己注册的流图节点么？

**Comment by TomHuangCN** [comment]
```js
Flow.registerNode(name, {
// 参考：https://lark.alipay.com/antv/rslism/anchor
anchor,
// 绘制
draw(item) {
return keyShape;
},
}, extandShape);
```

就是这么注册节点，注册好后，node 数据模型里指定相应的 shape 就行：

```js
{
  shape: name
}
```

**Comment by Liuqing650** [comment]
@TomHuangCN 注册节点或者行为等时，前两个参数能明白，后面的 `extandShape` 参数应该怎么使用，文档没有说明
