### ISSUE TITLE
g6-editor源码是基于react的吗？

### ISSUE THREAD

**Issue by liekkas** [antvis/g6-editor#14]
我用vue，拖拽节点完全不生效。假如不是能否提供一个原生js的例子呢？

**Comment by liekkas** [comment]
表现情况：无法连线
![walk](https://user-images.githubusercontent.com/778747/42156701-589a6b02-7e1e-11e8-97e7-4fa1ab082cdd.gif)

引入的时候报了一个错：
Cannot read property 'enable' of undefined

**Comment by neoni123** [comment]
大兄弟，我在vue中使用时也遇到这个问题，能否请教一下怎么解决的？

**Comment by sansizl** [comment]
您好，我在vue中使用g6-editor时遇到了一些问题，官方demo是react实现的，请问一下您在vue中使用g6-editor是怎么引入的。。
