### ISSUE TITLE
授权

### ISSUE THREAD

**Issue by lx3xun** [antvis/g6-editor#25]
您好：

得到授权后，代码中modelFlow.js 这些会提供源码吗？

**Comment by TomHuangCN** [comment]
会提供使用权，不会提供源码。

**Comment by zichen-cici** [comment]
![a0c8d75dc6cf31c9b541128f0eb184b](https://user-images.githubusercontent.com/13568082/49414243-ab4aa980-f7ad-11e8-91f2-ec02deb6e651.png)
请问这个权限的申请是在哪里申请的
