### ISSUE TITLE
商业使用的授权协议

### ISSUE THREAD

**Issue by nameliuqi** [antvis/g6-editor#33]
请问：
- 在经过一些本地适配后感觉g6 editor能作为实际产品中的一部分后改如何获得授权，授权协议是怎样的（我们老大已经发邮件了但是没有回复）？
- 是否受@antv/g6-plugins的GPL协议约束？（minimap貌似是g6 plugins里面的东西）

**Comment by TomHuangCN** [comment]
* 查收一下邮件
* G6 2.0 的插件在 [@antv/g6/plugins ](https://github.com/antvis/g6/tree/master/plugins) 证书和 G6 项目一致

**Comment by nameliuqi** [comment]
已经确认，谢谢大佬

**Comment by dxq613** [comment]
不再支持商业授权，谢谢
