### ISSUE TITLE
能不能想tree那样支持上下的脑图

### ISSUE THREAD

**Issue by jsformat** [antvis/g6-editor#50]
现在只支持左右的布局，能不能实现上下的布局

**Comment by TomHuangCN** [comment]
脑图只有左右布局

**Comment by jsformat** [comment]
通过g6可以定义脑图树，那个脑图树，支持拖拽么，启用拖拽行为后就会报错。

**Comment by TomHuangCN** [comment]
用 G6 做，所有的交互要自己基于基础事件做。behaviour.analysis 这个插件的拖拽应该只适用于 graph，不适用于 tree。

**Comment by jsformat** [comment]
用g6做出来的节点树，怎么像脑图的节点那样，拖拽到另一节点附近会自动吸附到该节点呢，大概是什么思路，能请教下么
