### ISSUE TITLE
请问下现在还能进行商用化申请吗？

### ISSUE THREAD

**Issue by tdida** [antvis/g6-editor#74]
请问下现在还能进行商用化申请吗？

**Comment by dxq613** [comment]
你好，我们最近在重新梳理 G6-Editor 的功能和定位，基于现有的版本可以商业化。但是现有的版本不会开源。

**Comment by tdida** [comment]
好的，期待g6-editor后续发展

**Comment by fallowu** [comment]
> 你好，我们最近在重新梳理 G6-Editor 的功能和定位，基于现有的版本可以商业化。但是现有的版本不会开源。

是可以商用，不用申请了吗？

**Comment by dxq613** [comment]
不再支持商业授权申请，谢谢。
